name:                TodoTxt
version:             1.0.0
github:              "PascalLG/todotxt-hs"
license:             MIT
author:              "Pascal Levy"
maintainer:          "pascal.levy@aequans.com"
copyright:           "2018 Pascal Levy"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/PascalLG/todotxt-hs#readme>

dependencies:
- base >= 4.7 && < 5
- directory >= 1.3
- filepath
- text
- time

library:
  source-dirs: src

executables:
  TodoTxt-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - TodoTxt

tests:
  TodoTxt-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - TodoTxt
    - hspec
